-- SECTOR
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('1', 1, NULL);
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('385', 2, (SELECT id FROM sector WHERE code = '1'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('19', 1, (SELECT id FROM sector WHERE code = '1'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('18', 2, (SELECT id FROM sector WHERE code = '1'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('6', 3, (SELECT id FROM sector WHERE code = '1'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('342', 1, (SELECT id FROM sector WHERE code = '6'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('43', 2, (SELECT id FROM sector WHERE code = '6'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('42', 3, (SELECT id FROM sector WHERE code = '6'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('40', 4, (SELECT id FROM sector WHERE code = '6'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('39', 5, (SELECT id FROM sector WHERE code = '6'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('437', 6, (SELECT id FROM sector WHERE code = '6'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('378', 7, (SELECT id FROM sector WHERE code = '6'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('13', 4, (SELECT id FROM sector WHERE code = '1'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('389', 1, (SELECT id FROM sector WHERE code = '13'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('390', 3, (SELECT id FROM sector WHERE code = '13'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('98', 4, (SELECT id FROM sector WHERE code = '13'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('101', 5, (SELECT id FROM sector WHERE code = '13'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('392', 6, (SELECT id FROM sector WHERE code = '13'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('394', 7, (SELECT id FROM sector WHERE code = '13'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('341', 8, (SELECT id FROM sector WHERE code = '13'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('99', 9, (SELECT id FROM sector WHERE code = '13'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('12', 5, (SELECT id FROM sector WHERE code = '1'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('94', 1, (SELECT id FROM sector WHERE code = '12'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('91', 2, (SELECT id FROM sector WHERE code = '12'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('224', 3, (SELECT id FROM sector WHERE code = '12'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('97', 4, (SELECT id FROM sector WHERE code = '12'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('271', 1, (SELECT id FROM sector WHERE code = '97'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('269', 2, (SELECT id FROM sector WHERE code = '97'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('230', 3, (SELECT id FROM sector WHERE code = '97'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('93', 5, (SELECT id FROM sector WHERE code = '12'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('508', 6, (SELECT id FROM sector WHERE code = '12'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('227', 7, (SELECT id FROM sector WHERE code = '12'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('11', 6, (SELECT id FROM sector WHERE code = '1'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('67', 1, (SELECT id FROM sector WHERE code = '11'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('263', 2, (SELECT id FROM sector WHERE code = '11'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('267', 3, (SELECT id FROM sector WHERE code = '11'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('542', 4, (SELECT id FROM sector WHERE code = '11'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('75', 1, (SELECT id FROM sector WHERE code = '542'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('62', 2, (SELECT id FROM sector WHERE code = '542'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('69', 3, (SELECT id FROM sector WHERE code = '542'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('66', 4, (SELECT id FROM sector WHERE code = '542'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('9', 7, (SELECT id FROM sector WHERE code = '1'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('54', 1, (SELECT id FROM sector WHERE code = '9'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('556', 2, (SELECT id FROM sector WHERE code = '9'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('559', 3, (SELECT id FROM sector WHERE code = '9'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('55', 1, (SELECT id FROM sector WHERE code = '559'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('57', 2, (SELECT id FROM sector WHERE code = '559'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('53', 3, (SELECT id FROM sector WHERE code = '559'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('560', 4, (SELECT id FROM sector WHERE code = '9'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('5', 8, (SELECT id FROM sector WHERE code = '1'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('148', 1, (SELECT id FROM sector WHERE code = '5'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('150', 2, (SELECT id FROM sector WHERE code = '5'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('145', 3, (SELECT id FROM sector WHERE code = '5'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('7', 9, (SELECT id FROM sector WHERE code = '1'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('44', 1, (SELECT id FROM sector WHERE code = '7'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('45', 2, (SELECT id FROM sector WHERE code = '7'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('8', 10, (SELECT id FROM sector WHERE code = '1'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('337', 1, (SELECT id FROM sector WHERE code = '8'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('51', 2, (SELECT id FROM sector WHERE code = '8'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('47', 3, (SELECT id FROM sector WHERE code = '8'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('3', 2, NULL);
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('37', 1, (SELECT id FROM sector WHERE code = '3'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('29', 2, (SELECT id FROM sector WHERE code = '3'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('33', 3, (SELECT id FROM sector WHERE code = '3'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('2', 3, NULL);
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('25', 1, (SELECT id FROM sector WHERE code = '2'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('35', 2, (SELECT id FROM sector WHERE code = '2'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('28', 3, (SELECT id FROM sector WHERE code = '2'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('581', 1, (SELECT id FROM sector WHERE code = '28'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('576', 2, (SELECT id FROM sector WHERE code = '28'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('121', 3, (SELECT id FROM sector WHERE code = '28'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('122', 4, (SELECT id FROM sector WHERE code = '28'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('22', 4, (SELECT id FROM sector WHERE code = '2'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('141', 5, (SELECT id FROM sector WHERE code = '2'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('21', 6, (SELECT id FROM sector WHERE code = '2'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('111', 1, (SELECT id FROM sector WHERE code = '21'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('114', 2, (SELECT id FROM sector WHERE code = '21'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('112', 3, (SELECT id FROM sector WHERE code = '21'));
INSERT INTO sector (code, order_no, parent_sector_id) VALUES ('113', 4, (SELECT id FROM sector WHERE code = '21'));

-- TRANSLATION (ENG)
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '1', 'ENG', 'Manufacturing');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '19', 'ENG', 'Construction materials');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '18', 'ENG', 'Electronics and Optics');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '6', 'ENG', 'Food and Beverage');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '342', 'ENG', 'Bakery & confectionery products');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '43', 'ENG', 'Beverages');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '42', 'ENG', 'Fish & fish products');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '40', 'ENG', 'Meat & meat products');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '39', 'ENG', 'Milk & dairy products');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '437', 'ENG', 'Other');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '378', 'ENG', 'Sweets & snack food');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '13', 'ENG', 'Furniture');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '389', 'ENG', 'Bathroom/sauna');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '385', 'ENG', 'Bedroom');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '390', 'ENG', 'Children’s room');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '98', 'ENG', 'Kitchen');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '101', 'ENG', 'Living room');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '392', 'ENG', 'Office');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '394', 'ENG', 'Other (Furniture)');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '341', 'ENG', 'Outdoor');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '99', 'ENG', 'Project furniture');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '12', 'ENG', 'Machinery');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '94', 'ENG', 'Machinery components');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '91', 'ENG', 'Machinery equipment/tools');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '224', 'ENG', 'Manufacture of machinery');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '97', 'ENG', 'Maritime');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '271', 'ENG', 'Aluminium and steel workboats');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '269', 'ENG', 'Boat/Yacht building');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '230', 'ENG', 'Ship repair and conversion');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '93', 'ENG', 'Metal structures');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '508', 'ENG', 'Other');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '227', 'ENG', 'Repair and maintenance service');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '11', 'ENG', 'Metalworking');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '67', 'ENG', 'Construction of metal structures');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '263', 'ENG', 'Houses and buildings');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '267', 'ENG', 'Metal products');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '542', 'ENG', 'Metal works');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '75', 'ENG', 'CNC-machining');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '62', 'ENG', 'Forgings, Fasteners');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '69', 'ENG', 'Gas, Plasma, Laser cutting');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '66', 'ENG', 'MIG, TIG, Aluminum welding');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '9', 'ENG', 'Plastic and Rubber');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '54', 'ENG', 'Packaging');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '556', 'ENG', 'Plastic goods');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '559', 'ENG', 'Plastic processing technology');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '55', 'ENG', 'Blowing');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '57', 'ENG', 'Moulding');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '53', 'ENG', 'Plastics welding and processing');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '560', 'ENG', 'Plastic profiles');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '5', 'ENG', 'Printing');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '148', 'ENG', 'Advertising');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '150', 'ENG', 'Book/Periodicals printing');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '145', 'ENG', 'Labelling and packaging printing');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '7', 'ENG', 'Textile and Clothing');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '44', 'ENG', 'Clothing');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '45', 'ENG', 'Textile');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '8', 'ENG', 'Wood');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '337', 'ENG', 'Other (Wood)');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '51', 'ENG', 'Wooden building materials');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '47', 'ENG', 'Wooden houses');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '3', 'ENG', 'Other');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '37', 'ENG', 'Creative industries');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '29', 'ENG', 'Energy technology');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '33', 'ENG', 'Environment');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '2', 'ENG', 'Service');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '25', 'ENG', 'Business services');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '35', 'ENG', 'Engineering');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '28', 'ENG', 'Information Technology and Telecommunications');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '581', 'ENG', 'Data processing, Web portals, E-marketing');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '576', 'ENG', 'Programming, Consultancy');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '121', 'ENG', 'Software, Hardware');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '122', 'ENG', 'Telecommunications');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '22', 'ENG', 'Tourism');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '141', 'ENG', 'Translation services');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '21', 'ENG', 'Transport and Logistics');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '111', 'ENG', 'Air');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '114', 'ENG', 'Rail');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '112', 'ENG', 'Road');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '113', 'ENG', 'Water');
