-- SECTOR
INSERT INTO sector (code, order_no) VALUES ('1', 1);
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('385', 2, '1');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('19', 1, '1');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('18', 2, '1');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('6', 3, '1');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('342', 1, '6');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('43', 2, '6');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('42', 3, '6');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('40', 4, '6');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('39', 5, '6');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('437', 6, '6');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('378', 7, '6');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('13', 4, '1');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('389', 1, '13');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('390', 3, '13');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('98', 4, '13');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('101', 5, '13');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('392', 6, '13');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('394', 7, '13');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('341', 8, '13');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('99', 9, '13');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('12', 5, '1');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('94', 1, '12');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('91', 2, '12');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('224', 3, '12');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('97', 4, '12');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('271', 1, '97');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('269', 2, '97');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('230', 3, '97');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('93', 5, '12');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('508', 6, '12');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('227', 7, '12');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('11', 6, '1');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('67', 1, '11');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('263', 2, '11');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('267', 3, '11');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('542', 4, '11');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('75', 1, '542');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('62', 2, '542');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('69', 3, '542');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('66', 4, '542');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('9', 7, '1');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('54', 1, '9');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('556', 2, '9');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('559', 3, '9');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('55', 1, '559');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('57', 2, '559');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('53', 3, '559');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('560', 4, '9');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('5', 8, '1');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('148', 1, '5');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('150', 2, '5');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('145', 3, '5');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('7', 9, '1');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('44', 1, '7');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('45', 2, '7');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('8', 10, '1');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('337', 1, '8');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('51', 2, '8');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('47', 3, '8');
INSERT INTO sector (code, order_no) VALUES ('3', 2);
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('37', 1, '3');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('29', 2, '3');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('33', 3, '3');
INSERT INTO sector (code, order_no) VALUES ('2', 3);
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('25', 1, '2');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('35', 2, '2');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('28', 3, '2');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('581', 1, '28');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('576', 2, '28');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('121', 3, '28');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('122', 4, '28');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('22', 4, '2');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('141', 5, '2');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('21', 6, '2');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('111', 1, '21');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('114', 2, '21');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('112', 3, '21');
INSERT INTO sector (code, order_no, parent_sector_code) VALUES ('113', 4, '21');

-- TRANSLATION (ENG)
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '1', 'ENG', 'Manufacturing');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '19', 'ENG', 'Construction materials');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '18', 'ENG', 'Electronics and Optics');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '6', 'ENG', 'Food and Beverage');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '342', 'ENG', 'Bakery & confectionery products');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '43', 'ENG', 'Beverages');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '42', 'ENG', 'Fish & fish products');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '40', 'ENG', 'Meat & meat products');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '39', 'ENG', 'Milk & dairy products');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '437', 'ENG', 'Other');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '378', 'ENG', 'Sweets & snack food');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '13', 'ENG', 'Furniture');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '389', 'ENG', 'Bathroom/sauna');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '385', 'ENG', 'Bedroom');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '390', 'ENG', 'Children’s room');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '98', 'ENG', 'Kitchen');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '101', 'ENG', 'Living room');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '392', 'ENG', 'Office');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '394', 'ENG', 'Other (Furniture)');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '341', 'ENG', 'Outdoor');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '99', 'ENG', 'Project furniture');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '12', 'ENG', 'Machinery');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '94', 'ENG', 'Machinery components');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '91', 'ENG', 'Machinery equipment/tools');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '224', 'ENG', 'Manufacture of machinery');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '97', 'ENG', 'Maritime');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '271', 'ENG', 'Aluminium and steel workboats');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '269', 'ENG', 'Boat/Yacht building');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '230', 'ENG', 'Ship repair and conversion');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '93', 'ENG', 'Metal structures');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '508', 'ENG', 'Other');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '227', 'ENG', 'Repair and maintenance service');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '11', 'ENG', 'Metalworking');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '67', 'ENG', 'Construction of metal structures');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '263', 'ENG', 'Houses and buildings');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '267', 'ENG', 'Metal products');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '542', 'ENG', 'Metal works');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '75', 'ENG', 'CNC-machining');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '62', 'ENG', 'Forgings, Fasteners');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '69', 'ENG', 'Gas, Plasma, Laser cutting');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '66', 'ENG', 'MIG, TIG, Aluminum welding');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '9', 'ENG', 'Plastic and Rubber');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '54', 'ENG', 'Packaging');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '556', 'ENG', 'Plastic goods');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '559', 'ENG', 'Plastic processing technology');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '55', 'ENG', 'Blowing');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '57', 'ENG', 'Moulding');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '53', 'ENG', 'Plastics welding and processing');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '560', 'ENG', 'Plastic profiles');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '5', 'ENG', 'Printing');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '148', 'ENG', 'Advertising');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '150', 'ENG', 'Book/Periodicals printing');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '145', 'ENG', 'Labelling and packaging printing');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '7', 'ENG', 'Textile and Clothing');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '44', 'ENG', 'Clothing');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '45', 'ENG', 'Textile');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '8', 'ENG', 'Wood');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '337', 'ENG', 'Other (Wood)');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '51', 'ENG', 'Wooden building materials');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '47', 'ENG', 'Wooden houses');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '3', 'ENG', 'Other');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '37', 'ENG', 'Creative industries');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '29', 'ENG', 'Energy technology');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '33', 'ENG', 'Environment');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '2', 'ENG', 'Service');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '25', 'ENG', 'Business services');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '35', 'ENG', 'Engineering');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '28', 'ENG', 'Information Technology and Telecommunications');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '581', 'ENG', 'Data processing, Web portals, E-marketing');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '576', 'ENG', 'Programming, Consultancy');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '121', 'ENG', 'Software, Hardware');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '122', 'ENG', 'Telecommunications');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '22', 'ENG', 'Tourism');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '141', 'ENG', 'Translation services');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '21', 'ENG', 'Transport and Logistics');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '111', 'ENG', 'Air');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '114', 'ENG', 'Rail');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '112', 'ENG', 'Road');
INSERT INTO translation (translation_group, translation_key, language, translation) VALUES ('sector', '113', 'ENG', 'Water');
